#ifndef BUS_I2C_H
#define BUS_I2C_H

#include <Arduino.h>

/*
 * BusI2C_Scanner
 *
 * SONDE UNE FOIS LES ADRESSES CONNUES DU BUS WIRE1 (QWIIC) ET
 * MEMORISE CELLES QUI ONT REPONDU. A APPELER DANS setup() APRES
 * Wire1.begin() ET AVANT L'INITIALISATION DES MODULES.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void BusI2C_Scanner(void);

/*
 * BusI2C_EstPresent
 *
 * INDIQUE SI UN PERIPHERIQUE A REPONDU A L'ADRESSE DEMANDEE LORS
 * DU SCAN. AUCUNE TRANSACTION N'EST EMISE : LA REPONSE VIENT DU
 * CACHE, L'APPEL EST DONC NON BLOQUANT.
 *
 * PARAMETRE :
 * adresse — ADRESSE I2C 7 BITS (EX: ADRESSE_LIDAR)
 *
 * RETOUR :
 * VRAI SI LE PERIPHERIQUE EST PRESENT
 */
bool BusI2C_EstPresent(uint8_t adresse);

/*
 * BusI2C_Tracer
 *
 * AFFICHE SUR LE PORT SERIE LE RESULTAT DU DERNIER SCAN : ADRESSE,
 * PRESENCE ET DUREE DU SONDAGE. A APPELER DEPUIS loop() : LE MONITEUR
 * NE S'ATTACHE QU'APRES L'EXECUTION DE setup().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void BusI2C_Tracer(void);

#endif