#ifndef EVITEMENT_H
#define EVITEMENT_H

#include <Arduino.h>

/*
 * Evitement_Initialiser
 *
 * PLACE LA MANOEUVRE D'EVITEMENT AU REPOS. A APPELER UNE FOIS DANS
 * setup(), APRES Securite_Initialiser().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Evitement_Initialiser(void);

/*
 * Evitement_MettreAJour
 *
 * FAIT PROGRESSER LE CONTOURNEMENT : SONDAGE, ROTATION VERS LE COTE
 * DEGAGE, DIAGONALE D'ECARTEMENT, ROTATION DE REMISE PARALLELE,
 * SEGMENT PARALLELE A LA LIGNE, PUIS ROTATION DE RETOUR VERS ELLE.
 * CHAQUE ETAPE EST PRECEDEE D'UNE IMMOBILISATION.
 * NE S'ENGAGE QU'EN MODE AUTONOME, VEHICULE IMMOBILISE PAR LE VETO.
 * NON BLOQUANTE. A APPELER A CHAQUE ITERATION DE loop().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Evitement_MettreAJour(void);

#endif
