#ifndef IMU_H
#define IMU_H

#include <Arduino.h>

/*
 * Imu_Initialiser
 *
 * REVEILLE LE CAPTEUR MPU-6050 EN ECRIVANT 0 DANS LE REGISTRE
 * PWR_MGMT_1. LE CAPTEUR EST SUR LE BUS I2C WIRE1 (0x68).
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Imu_Initialiser(void);

/*
 * Imu_Calibrer
 *
 * MESURE L'OFFSET DU GYROSCOPE AXE Z EN MOYENNANT IMU_CAL_ECHANTILLONS
 * LECTURES, SOIT ENVIRON UNE SECONDE. LE VEHICULE DOIT ETRE IMMOBILE.
 * SI LA DISPERSION DES ECHANTILLONS TRAHIT UN MOUVEMENT, L'OFFSET
 * PRECEDENT EST CONSERVE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Imu_Calibrer(void);

/*
 * Imu_CalibrerRapide
 *
 * REETABLIT LE ZERO DU GYROSCOPE SUR UN ECHANTILLONNAGE COURT, DE L'ORDRE
 * DE QUATRE-VINGTS MILLISECONDES. DESTINEE A ETRE REJOUEE AVANT CHAQUE
 * MOUVEMENT ASSERVI, LE VEHICULE ETANT ALORS A L'ARRET, POUR ANNULER LA
 * DERIVE THERMIQUE ACCUMULEE DEPUIS LE DEMARRAGE. MEME GARDE-FOU DE
 * DISPERSION QUE Imu_Calibrer.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Imu_CalibrerRapide(void);

/*
 * Imu_LireGyroZ
 *
 * LIT LA VITESSE ANGULAIRE SUR L'AXE Z, CORRIGEE PAR L'OFFSET
 * DE CALIBRATION. SENSIBILITE : 131 LSB PAR DEGRE/S (±250 DEG/S).
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * VITESSE ANGULAIRE EN DEGRES PAR SECONDE
 */
float Imu_LireGyroZ(void);

// RETOURNE VRAI SI LE MPU-6050 A REPONDU SUR LE BUS I2C A L'INITIALISATION.
bool Imu_EstPresent(void);

#endif