#ifndef LIDAR_H
#define LIDAR_H

#include <Arduino.h>

/*
 * Lidar_Initialiser
 *
 * PREPARE LE MODULE LIDAR TF-LUNA. LE CAPTEUR COMMUNIQUE EN I2C
 * SUR LE BUS WIRE1 (QWIIC), ADRESSE 0x10. LE MODE I2C EST
 * SELECTIONNE MATERIELLEMENT : LA BROCHE CFG DU CAPTEUR DOIT
 * ETRE RELIEE A LA MASSE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Lidar_Initialiser(void);

/*
 * Lidar_EstPresent
 *
 * VERIFIE QUE LE CAPTEUR ACQUITTE SUR LE BUS I2C. UTILE POUR
 * VALIDER LE CABLAGE ET LA BROCHE CFG.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * true SI LE CAPTEUR REPOND, false SINON
 */
bool Lidar_EstPresent(void);

/*
 * Lidar_MettreAJour
 *
 * LIT UNE MESURE (CADENCEE, NON BLOQUANTE) ET MET A JOUR LA
 * DISTANCE EN CACHE. DOIT ETRE APPELE A CHAQUE ITERATION DE
 * LOOP().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Lidar_MettreAJour(void);

/*
 * Lidar_DistanceCm
 *
 * RETOURNE LA DERNIERE DISTANCE FRONTALE MESUREE, EN CM.
 * -1 SI LA LECTURE EST INVALIDE : SIGNAL TROP FAIBLE, SATURATION,
 * HORS PORTEE, OU CAPTEUR ABSENT.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * DISTANCE EN CM, OU -1
 */
int Lidar_DistanceCm(void);

/*
 * Lidar_MesurerMaintenant
 *
 * DECLENCHE IMMEDIATEMENT UNE LECTURE I2C, SANS PASSER PAR LE CACHE
 * PERIODIQUE. DESTINEE AU SONDAGE PAR SECTEURS, QUI DOIT ASSOCIER CHAQUE
 * DISTANCE A L'ORIENTATION EXACTE DU SERVO AU MOMENT DE LA MESURE.
 *
 * PARAMETRE :
 * distCm : RECOIT LA DISTANCE MESUREE, EN CM, SI LA LECTURE EST VALIDE
 *
 * RETOUR :
 * true SI LA LECTURE EST VALIDE, false SINON
 */
bool Lidar_MesurerMaintenant(int &distCm);

#endif
