#ifndef OBSTACLE_H
#define OBSTACLE_H

#include <Arduino.h>

#define SECTEUR_GAUCHE  0
#define SECTEUR_CENTRE  1
#define SECTEUR_DROITE  2
#define NB_SECTEURS     3

/*
 * Obstacle_Initialiser
 *
 * PREPARE LA DETECTION D'OBSTACLES ET PLACE LE SERVO DROIT DEVANT.
 * A APPELER UNE FOIS DANS setup(), APRES ServoLidar_Initialiser().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Obstacle_Initialiser(void);

/*
 * Obstacle_MettreAJour
 *
 * REEVALUE LA DISTANCE FRONTALE ET FAIT PROGRESSER LE SONDAGE EN COURS,
 * S'IL Y EN A UN. NON BLOQUANTE. A APPELER A CHAQUE ITERATION DE loop().
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Obstacle_MettreAJour(void);

/*
 * Obstacle_DistanceFrontaleCm
 *
 * RETOURNE LA DISTANCE DE L'OBSTACLE LE PLUS PROCHE DEVANT LE VEHICULE.
 * RETIENT LA PLUS PETITE DES MESURES VALIDES DE L'ULTRASON ET DU LIDAR.
 * BORNEE A ULTRASON_DISTANCE_MAX, VALEUR QUI SIGNIFIE VOIE DEGAGEE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * DISTANCE EN CM
 */
int Obstacle_DistanceFrontaleCm(void);

/*
 * Obstacle_EstDetecte
 *
 * INDIQUE SI UN OBSTACLE SE TROUVE A MOINS DE OBSTACLE_SEUIL_CM
 * DEVANT LE VEHICULE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * true SI UN OBSTACLE EST SIGNALE, false SINON
 */
bool Obstacle_EstDetecte(void);

/*
 * Obstacle_LancerSondage
 *
 * DEMARRE UN SONDAGE DES TROIS SECTEURS : GAUCHE, CENTRE, DROITE.
 * LE SERVO REVIENT AU CENTRE A LA FIN. SANS EFFET SI UN SONDAGE EST
 * DEJA EN COURS OU SI LE LIDAR EST ABSENT. DUREE APPROXIMATIVE : 1 s.
 * LE VEHICULE DOIT ETRE A L'ARRET : EN MOUVEMENT, LES TROIS MESURES
 * DECRIRAIENT TROIS POSITIONS DIFFERENTES.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void Obstacle_LancerSondage(void);

/*
 * Obstacle_SondageEnCours
 *
 * INDIQUE SI UN SONDAGE EST EN COURS. LES DISTANCES PAR SECTEUR NE SONT
 * EXPLOITABLES QU'UNE FOIS LE SONDAGE TERMINE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * true SI UN SONDAGE EST EN COURS, false SINON
 */
bool Obstacle_SondageEnCours(void);

/*
 * Obstacle_DistanceSecteur
 *
 * RETOURNE LA DISTANCE RELEVEE DANS UN SECTEUR LORS DU DERNIER SONDAGE.
 *
 * PARAMETRE :
 * secteur : SECTEUR_GAUCHE, SECTEUR_CENTRE OU SECTEUR_DROITE
 *
 * RETOUR :
 * DISTANCE EN CM, OU -1 SI AUCUNE MESURE EXPLOITABLE
 */
int Obstacle_DistanceSecteur(int secteur);

/*
 * Obstacle_CoteLePlusDegage
 *
 * COMPARE LES DEUX SECTEURS LATERAUX DU DERNIER SONDAGE. UNE DIRECTION
 * SANS ECHO EST TRAITEE COMME DEGAGEE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * SECTEUR_GAUCHE OU SECTEUR_DROITE
 */
int Obstacle_CoteLePlusDegage(void);

#endif
