#ifndef TEST_LEDS_H
#define TEST_LEDS_H

#include <Arduino.h>

// Commenter la ligne suivante pour desactiver la demonstration au demarrage.
#define TEST_LEDS_ACTIF

/*
 * TestLeds_MettreAJour
 *
 * FAIT DEFILER UNE FOIS LES MODES DE BANDEAU, LES FEUX ET LES DEUX
 * CLIGNOTANTS, UNE SECONDE PAR ETAPE, POUR VALIDER LE CABLAGE ET
 * L'ORIENTATION DES BANDEAUX. NON BLOQUANTE : LA DEMONSTRATION SE
 * DEROULE DEPUIS loop() ET REND LA MAIN A LA FIN. SANS EFFET SI
 * TEST_LEDS_ACTIF N'EST PAS DEFINI.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * AUCUN
 */
void TestLeds_MettreAJour(void);

/*
 * TestLeds_EstActif
 *
 * INDIQUE SI LA DEMONSTRATION PILOTE ENCORE LES LEDS. TANT QU'ELLE EST
 * ACTIVE, L'APPELANT NE DOIT PAS IMPOSER SA PROPRE CONSIGNE DE VIRAGE.
 *
 * PARAMETRE :
 * AUCUN
 *
 * RETOUR :
 * true SI LA DEMONSTRATION EST EN COURS, false SINON
 */
bool TestLeds_EstActif(void);

#endif
